# Generated by Django 5.2.5 on 2025-08-23 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet_records', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='carbs',
            new_name='carbohydrates',
        ),
    ]
