# Generated by Django 5.2.4 on 2025-08-05 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsession',
            name='plan',
        ),
        migrations.DeleteModel(
            name='TrainingPlan',
        ),
        migrations.DeleteModel(
            name='TrainingSession',
        ),
    ]
