# Generated by Django 5.2.4 on 2025-08-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_trainingsession_target_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
