# Generated by Django 5.2.4 on 2025-08-05 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_trainingsession_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='goal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='due_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
