# Generated by Django 5.2.4 on 2025-08-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_trainingplan_goal_trainingsession_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
